### ISSUE TITLE
Firebase tooling requires upgrade in order to work

### ISSUE THREAD

**Issue by hmavrodiev** [balupton/automated-trading#1]
uploads and downloads. You can keep these rules in your project directory
and publish them with firebase deploy.

? What file should be used for Storage Rules? storage.rules

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

+  Firebase initialization complete!

C:\Users\HMA\google2>firebase deploy --only functions
1

=== Deploying to 'automated-trading-e6cfe'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
+  runtimeconfig: all necessary APIs are enabled
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (35.69 KB) for uploading
+  functions: functions folder uploaded successfully
i  starting release process (may take several minutes)...
i  functions: creating function version...
i  functions: creating function createUser...
i  functions: creating function parse...
i  functions: creating function bitfinex_createService...
i  functions: creating function bitfinex_fetchBalances...
i  functions: creating function bitfinex_createOrder...
i  functions: creating function itbit_createService...
i  functions: creating function itbit_fetchTicker...
i  functions: creating function itbit_fetchWallets...
i  functions: creating function itbit_fetchWallet...
i  functions: creating function itbit_createOrder...
i  functions: creating function drivewealth_createService...
i  functions: creating function drivewealth_createSession...
i  functions: creating function drivewealth_getAccountSummary...
i  functions: creating function drivewealth_getAccount...
i  functions: creating function drivewealth_getInstrument...
i  functions: creating function drivewealth_createOrder...
!  functions[createUser]: Deploy Error: Function load error: Code in file index.
js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: EIO: i/o error, read
    at Error (native)
    at Object.fs.readSync (fs.js:732:19)
    at tryReadSync (fs.js:487:20)
    at Object.fs.readFileSync (fs.js:527:19)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
+  functions[version]: Successful create operation.
+  functions[parse]: Successful create operation.
+  functions[bitfinex_createService]: Successful create operation.
+  functions[bitfinex_fetchBalances]: Successful create operation.
+  functions[bitfinex_createOrder]: Successful create operation.
+  functions[itbit_createService]: Successful create operation.
+  functions[itbit_fetchTicker]: Successful create operation.
+  functions[itbit_fetchWallets]: Successful create operation.
+  functions[itbit_fetchWallet]: Successful create operation.
+  functions[itbit_createOrder]: Successful create operation.
+  functions[drivewealth_createService]: Successful create operation.
+  functions[drivewealth_createSession]: Successful create operation.
+  functions[drivewealth_getAccountSummary]: Successful create operation.
+  functions[drivewealth_getAccount]: Successful create operation.
+  functions[drivewealth_getInstrument]: Successful create operation.
+  functions[drivewealth_createOrder]: Successful create operation.
+  functions: 16 function(s) deployed successfully.

Functions deploy had errors. To continue deploying other features (such as datab
ase), run:
    firebase deploy --except functions

Error: Functions did not deploy properly.

C:\Users\HMA\google2>http -f POST https://VALUE.cloudfunctions.net/createUser \
'http' is not recognized as an internal or external command,
operable program or batch file.

**Comment by stamun8** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\HMA\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@5.5.1
3 info using node@v8.8.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle automated-trading@1.0.0~predeploy: automated-trading@1.0.0
6 info lifecycle automated-trading@1.0.0~deploy: automated-trading@1.0.0
7 verbose lifecycle automated-trading@1.0.0~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle automated-trading@1.0.0~deploy: PATH: C:\Users\HMA\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;c:\Users\HMA\automated-trading2\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\WinSCP\;C:\Program Files\nodejs\;C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\HMA\AppData\Local\Programs\Python\Python36-32\;C:\Program Files\Docker Toolbox;C:\Users\HMA\AppData\Roaming\npm
9 verbose lifecycle automated-trading@1.0.0~deploy: CWD: c:\Users\HMA\automated-trading2
10 silly lifecycle automated-trading@1.0.0~deploy: Args: [ '/d /s /c',
10 silly lifecycle   'cd ./firebase && firebase deploy --only functions && cd ../' ]
11 silly lifecycle automated-trading@1.0.0~deploy: Returned: code: 1  signal: null
12 info lifecycle automated-trading@1.0.0~deploy: Failed to exec deploy script
13 verbose stack Error: automated-trading@1.0.0 deploy: `cd ./firebase && firebase deploy --only functions && cd ../`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\HMA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\HMA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid automated-trading@1.0.0
15 verbose cwd c:\Users\HMA\automated-trading2
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HMA\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
18 verbose node v8.8.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error automated-trading@1.0.0 deploy: `cd ./firebase && firebase deploy --only functions && cd ../`
22 error Exit status 1
23 error Failed at the automated-trading@1.0.0 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by balupton** [comment]
Firebase keeps updating their API, so this repository will no longer work with the latest firebase APIs.

A few people have upgraded the repo to work with the latest firebase, but they never bothered to submit their changes.

I've been working on accomplishing the roadmap via set of new projects.

If anyone wishes to get this project up to date with firebase in the meantime, that would be helpful.
